/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reencrypt;
import burp.api.montoya.BurpExtension;
import burp.api.montoya.MontoyaApi;
import burp.api.montoya.ui.editor.extension.EditorCreationContext;
import burp.api.montoya.ui.editor.extension.EditorMode;
import burp.api.montoya.ui.editor.extension.ExtensionProvidedHttpRequestEditor;
import burp.api.montoya.ui.editor.extension.ExtensionProvidedHttpResponseEditor;
import burp.api.montoya.ui.editor.extension.HttpRequestEditorProvider;
import burp.api.montoya.ui.editor.extension.HttpResponseEditorProvider;

public class App implements BurpExtension {
    public static final String name = "Re:Encrypt";

    public void initialize(MontoyaApi api) {
        
        var config = new Config(api.persistence());
        var reEncrypt = new ReEncrypt(config);
        
        api.extension().setName(name);
        api.userInterface().registerSuiteTab(name, new ExtensionTab(config).uiComponent());
        api.userInterface().registerHttpRequestEditorProvider(new HttpRequestEditorProvider() {
            public ExtensionProvidedHttpRequestEditor provideHttpRequestEditor(EditorCreationContext creationContext) {
                return new RequestTab(api, reEncrypt, creationContext.editorMode() == EditorMode.READ_ONLY);
            }
        });
        api.userInterface().registerHttpResponseEditorProvider(new HttpResponseEditorProvider() {
            public ExtensionProvidedHttpResponseEditor provideHttpResponseEditor(
                    EditorCreationContext creationContext) {
                return new ResponseTab(api, reEncrypt, creationContext.editorMode() == EditorMode.READ_ONLY);
            }            
        });
        // TODO: check if this is the one that shows the changes
        api.proxy().registerRequestHandler(new ProxyHandler(reEncrypt));
        api.intruder().registerPayloadProcessor(new IntruderHandler(reEncrypt));
    }

    
}
