/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.gradleup.shadow") version "9.3.0" // This is necessary to make the hashing library net.openhft:zero-allocation-hashing work in Burp Suite
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("net.portswigger.burp.extensions:montoya-api:2025.8")
    implementation("net.openhft:zero-allocation-hashing:0.27ea1")
    // JSON for persistence + export/import. Montoya ships a JSON API, but it is backed by a factory
    // Burp injects at runtime, so it is null under unit tests - persistence would be untestable.
    implementation("com.google.code.gson:gson:2.11.0")
    
    // Testing
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.jar {
    // Disable the standard jar task, to avoid generating 2 jar files
    enabled = false
}

tasks.shadowJar {
    // This is necessary to make the hashing library net.openhft:zero-allocation-hashing work in Burp Suite
    relocate("net.openhft.hashing", "reencrypt.shaded.hashing")
    relocate("com.google.gson", "reencrypt.shaded.gson")
    archiveClassifier.set("encrypt")
    archiveBaseName.set("re")
}

val main = "reencrypt.App"

application {
    // Define the main class for the application.
    mainClass.set(main)
}

tasks.withType<Jar> {
    manifest {
        attributes("Main-Class" to "$main")
    }
    archiveBaseName.set("re")
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
}
