/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    // testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")
    implementation("net.portswigger.burp.extensions:montoya-api:2023.1")
}
val main = "reencrypt.App"

application {
    // Define the main class for the application.
    mainClass.set(main)
}

tasks.withType<Jar> {
    manifest {
        attributes("Main-Class" to "$main")
    }
    archiveBaseName.set("reencrypt")
}

